version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env
